### PR TITLE
Update version of mem transitive dependency.

### PR DESCRIPTION
**Pull request by gikaragia**
### Overview
Package mem is a transitive dependency of package cgb-scripts. Since cgb-scripts is not updated yet to include the needed version of mem, we need to use the tool npm-force-resolutions to update it.

I am not sure if this is the best approach to update a transitive dependency, any other suggestions are welcome :)

### Testing
1. I created a zip file from the branch and installed it in a local test site.
2. Created a new SyntaxHighlighter block.
3. Visited the page which contained the blocks in the frontend.

### CODE REVIEW

**Comment by renatho** [comment]
And if we just sent a PR to the `cgb-scripts`?
It's a low severity (https://www.npmjs.com/advisories/1084). Maybe could we wait for it a little?

Or we could make fix it temporarily, make the PR and after accepted, we could remove :)

**Comment by donnchawp** [comment]
I was going to say we should wait for cgb-scripts to update but if they haven't updated since November they probably aren't going to update any time soon.
The version of mem that fixed this (4.0.0) was released a year ago according to the advisory. I vote we accept this PR and merge things whenever cgb-scripts updates.

**Comment by gikaragia** [comment]
Unfortunately mem comes as a dependency from cgb-scripts' webpack. There is a PR open to update webpack [here](https://github.com/ahmadawais/create-guten-block/pull/166). It seems that updating it is not trivial and last movement in it was last May. We could have this PR as a temporary solution and in the longrun drop the cgb-scripts dependency.

**Review by renatho — APPROVED** [review]
> We could have this PR as a temporary solution and in the longrun drop the cgb-scripts dependency.

I agree.

**Comment by donnchawp** [comment]
OK, I'll merge this then. :)

**Comment by renatho** [comment]
What do you think about create a reminder on Slack to check if this PR was merged on `cgb-scripts` in a few months?

**Pull request merged**
